name: CI Pipeline

on:
   push:
     branches:
      - main

jobs:
   build:
   
     runs-on: ubuntu-latest

     steps: 
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
        node-version: '15'

     - name: Install dependencies
       working-directory: ./codebase/rdicidr-0.1.0/
       run: npm install

     - name: Run ESLint
       working-directory: ./codebase/rdicidr-0.1.0/
       run: npm run lint

     - name: Run Prettier
       working-directory: ./codebase/rdicidr-0.1.0/
       run: npm install --save-dev prettier 
       #run: npm run prettier

     - name: Run Prettier2
       working-directory: ./codebase/rdicidr-0.1.0/
       #run: npm install --save-dev prettier 
       run: npm run prettier -- --write

     - name: Run tests
       working-directory: ./codebase/rdicidr-0.1.0/
       run: CI=true npm run test

     - name: build
       working-directory: ./codebase/rdicidr-0.1.0/
       run: npm run build

     - name: Build Docker image
       working-directory: ./codebase/rdicidr-0.1.0/
       run: docker build -t acreus.azurecr.io/my-app:v1 .
     
     - name: Login to ACR
       working-directory: ./codebase/rdicidr-0.1.0/
       run: echo ${{ secrets.ACR_PASSWORD }} | docker login acreus.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

     - name: Push Docker image to ACR
       working-directory: ./codebase/rdicidr-0.1.0/
       run: docker push acreus.azurecr.io/my-app:v1


       #added
